### ISSUE TITLE
bytes[i]='a' 赋值失败

### ISSUE THREAD

**Issue by bobo-boom** [SealSC/SealEVM#1]
发现一个问题：

solidity如下代码：

    function strConcat() public  returns (bytes memory ){

        string memory ret = new string(4);
        bytes memory  bret = bytes(ret);
        
        bret[0]= 'a';
        bret[1]= 'b';
        bret[2]= 'd';
        bret[3]= 'g';
            
        return bret;

  }

此函数通过SealEVM执行，结果为[0 0 0 0],通过remix执行的话结果是正常的， 0x61626467，希望作者可以定位一下，

**Comment by AKACoder** [comment]
fixed in this [commit](https://github.com/SealSC/SealEVM/commit/6b1f4ee97b95d800757d425d569959859c00d5b4)
