### ISSUE TITLE
Inappropriate code implementation of SealEVM gas prices

### ISSUE THREAD

**Issue by Alleysira** [SealSC/SealEVM#18]
Hi, I'm interested in the security of EVM implementations, so I fuzzed SealEVM with other EVM implementations, then I found that it seems there are lots of inconsistencies and conflicts regarding gas costs between SealEVM's implementation and Ethereum.
For example, according to [Ethereum official documentation](https://www.evm.codes/?fork=shanghai), the gas cost of opcode `0x00 STOP` should be `0`, but in [SealEVM's code](https://github.com/SealSC/SealEVM/blob/master/instructions/instructions.go), the gas cost of `STOP` is set to `3` in the default setting.

```go
func DefaultGasSetting() *GasSetting {
	gs := &GasSetting{}

	for i := range gs.ActionConstCost {
		gs.ActionConstCost[i] = 3
	}

	gs.ActionConstCost[opcodes.EXP] = 10
	gs.ActionConstCost[opcodes.SHA3] = 30
	gs.ActionConstCost[opcodes.LOG0] = 375
	gs.ActionConstCost[opcodes.LOG1] = 375 * 2
	gs.ActionConstCost[opcodes.LOG2] = 375 * 3
	gs.ActionConstCost[opcodes.LOG3] = 375 * 4
	gs.ActionConstCost[opcodes.LOG4] = 375 * 5
	gs.ActionConstCost[opcodes.SLOAD] = 800
	gs.ActionConstCost[opcodes.SSTORE] = 5000
	gs.ActionConstCost[opcodes.SELFDESTRUCT] = 30000

	gs.ActionConstCost[opcodes.CREATE] = 32000
	gs.ActionConstCost[opcodes.CREATE2] = 32000

	gs.DynamicCost.EXPBytesCost = 50
	gs.DynamicCost.SHA3ByteCost = 6
	gs.DynamicCost.MemoryByteCost = 2
	gs.DynamicCost.LogByteCost = 8

	return gs
}
```
And for some opcodes with dynamic gas, like `0X0A EXP`, `0X20 SHA3`, there are set to constant value `10` and `30` respectively，without additional dynamic cost charging. 
Considering that the gas mechanism directly impacts the execution and security of smart contracts, I believe that the aforementioned implementation should be reviewed and improved. Thanks.

**Comment by AKACoder** [comment]
I’m glad you’re interested in SealEVM and appreciate the valuable suggestions you’ve provided. I plan to create a separate GasSetting preset to address the suggestions you’ve made, but I cannot determine exactly when it will be completed. Therefore, I’ve decided to close this issue.

The main purpose of SealEVM is to provide an independent and customizable EVM execution module. While the DefaultGasSetting does not match Ethereum’s setting, it serves as a quick gas configuration and an illustrative example. Developers can load their own settings, such as fully Ethereum seamless settings, through the GasSetting field in the EVMParam struct.
