### ISSUE TITLE
为什么没有去掉依赖 go-ethereum 依赖

### ISSUE THREAD

**Issue by godeamon** [SealSC/SealEVM#20]
您好，看了咱们 EVM 实现的代码，目前我理解已经可以不依赖 go-ethereum 代码库了，现在还是依赖的，请问这样做是有什么考虑吗？

**Comment by AKACoder** [comment]
> 您好，看了咱们 EVM 实现的代码，目前我理解已经可以不依赖 go-ethereum 代码库了，现在还是依赖的，请问这样做是有什么考虑吗？

目前预编译合约还是用到了go-ethereum的代码，因此还保留了对它的依赖
