### ISSUE TITLE
SealEVM stack underflow  for opcode `CREATE2`

### ISSUE THREAD

**Issue by Alleysira** [SealSC/SealEVM#21]
According to [EIP-1014](https://eips.ethereum.org/EIPS/eip-1014) and [evm opcode](https://www.evm.codes/?fork=cancun), the opcode `CREATE2` (`0xf0`) should take 4 stack elements and calculate new address as 
```
initialisation_code = memory[offset:offset+size]
address = keccak256(0xff + sender_address + salt + keccak256(initialisation_code))[12:]
```
In SealEVM, the address is generated by func `CreateFixedAddress`, https://github.com/SealSC/SealEVM/blob/7e4a3eec9794a4dbdd923a425a993611d29c4285/instructions/closure.go#L205

where new address is generated by https://github.com/SealSC/SealEVM/blob/7e4a3eec9794a4dbdd923a425a993611d29c4285/example/memStorage.go#L53

I underestand this is for demonstration as it in `dir/example`, similar for `BALANCE`(`0X31`) etc.
But SealEVM set the stack depth requirement of `CREATE2` to `2` instead of `4` at https://github.com/SealSC/SealEVM/blob/7e4a3eec9794a4dbdd923a425a993611d29c4285/instructions/closure.go#L80

In the func `commonCreate`, it first pops 3 elements from stack.
https://github.com/SealSC/SealEVM/blob/7e4a3eec9794a4dbdd923a425a993611d29c4285/instructions/closure.go#L171-L177

This operation will raise a stack underflow error because the number of elements in the stack is insufficient to fulfill the requirements of the operation.

**Comment by AKACoder** [comment]
Merged!
Thank you for your code review and bug fixes!
@Alleysira
