### ISSUE TITLE
Excessive Gas Consumption Due to Index Out of Range Bug in SealEVM

### ISSUE THREAD

**Issue by Alleysira** [SealSC/SealEVM#27]
# Intro
Hello @AKACoder, I found an index out of range bug in the SealEVM repository at this [link](https://github.com/SealSC/SealEVM/blob/5fdcffacc30b71dae4efd4b4999735c011371d81/instructions/instructions.go#L163). This bug causes SealEVM to charge all the provided gas. If the execution consumes more gas than expected, it can lead to serious issues such as transaction failures, increased transaction costs, and potential denial of service (DoS) vulnerabilities.

# Bug description

When the deployed bytecode does not end with an opcode that is set  `finished: true` (e.g., `STOP`, `RETURN`, `REVERT`, `SELFDESTRUCT`), the sealevm will charge all of the provided gas and raise an index out of range error.

## Root cause

Check the function `ExecuteContract()`  in `SealEVM/instructions/instructions.go `.

```go
opCode := contract.Code[i.pc]
```

When the `for` loop keeps running and the bytecode do not end with `STOP`, `RETURN` ,`REVERT` or `SELFDESTRUCT`, `i.pc` will eventually reach `len(contract.Code)`, causing an index out of range error. This will lead to a panic, preventing the program from returning the correct `gas_left`.

# How to reproduce

## Set deployed bytecode

Simply pull the latest version of the sealevm and enter the `example` dir.

```shell
git clone https://github.com/SealSC/SealEVM.git
cd example
nano code.go
```

Change the ` var deployCode` in `example/code.go` to bytecode `6000600001`

```
 var deployCode, _ = hex.DecodeString("6000600001")
```

Where `6000600101` is the opcode as shown below:

```
PUSH1 0X00
PUSH1 0x00
ADD 0X00,0x00
```

## Add logging statement

Then add log statement to print the gas usage during the execution in `SealEVM/sealEVM.go `

```
import "log"

// add log at line 167
	execRet, gasLeft, err := e.instructions.ExecuteContract()
	log.Printf("gasleft %d", gasLeft)
	result.ResultData = execRet
```

Also in `SealEVM/instructions/instructions.go`

```go
import "log"

// add log in defer-recover statements.
	defer func() {
		if e := recover(); e != nil {
			log.Println(e)
			err = evmErrors.Panicked(e.(error))
		}
	}()

// add log at line 180
		log.Printf("pc %d len(contract.Code) %d", i.pc, len(contract.Code))
		opCode := contract.Code[i.pc]
```

## Run

```
cd example
go build -o sealevm
./sealevm
```

You can see that the `recover()` caught an index out of range error and sealevm charge all of the provided gas. 

## Result

![image-20240726201226678](https://github.com/user-attachments/assets/b179130a-9040-4085-a09f-67d34c790960)
## Expected result

Here is the result from `geth/evm 1.14.5-stable-0dd173a7`

```json
{"pc":0,"op":96,"gas":"0xffffff","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":2,"op":96,"gas":"0xfffffc","gasCost":"0x3","memSize":0,"stack":["0x0"],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":4,"op":1,"gas":"0xfffff9","gasCost":"0x3","memSize":0,"stack":["0x0","0x0"],"depth":1,"refund":0,"opName":"ADD"}
{"pc":5,"op":0,"gas":"0xfffff6","gasCost":"0x0","memSize":0,"stack":["0x0"],"depth":1,"refund":0,"opName":"STOP"}
{"output":"","gasUsed":"0x9"}
```

However, sealevm charged all of the provided gas. 

```json
{"pc":0,"op":96,"gas":"0xfffffc","gasCost":"0x3","memory":"0x","stack":null,"opName":"PUSH1"}
{"pc":2,"op":96,"gas":"0xfffff9","gasCost":"0x3","memory":"0x","stack":["0x0"],"opName":"PUSH1"}
{"pc":4,"op":1,"gas":"0xfffff6","gasCost":"0x3","memory":"0x","stack":["0x0","0x0"],"opName":"ADD"}
{"output":"","gasUsed":"0xffffff","exitOpcode":"STOP","error":""}
```

**Comment by AKACoder** [comment]
@Alleysira Thank you for your meticulous testing! The issue has been resolved in this commit [25f5f52](https://github.com/SealSC/SealEVM/commit/25f5f52b60a99d28bbb48cb0e12b6badb70cf792).
