### ISSUE TITLE
与uint256MAX按位与，运算完不还是自己吗？

### ISSUE THREAD

**Issue by wukoo** [SealSC/SealEVM#3]
https://github.com/SealSC/SealEVM/blob/1e2e076787dff706df96b32bffc0d5936e4d56da/evmInt256/evmInt256.go#L83-L86

看不太明白，想请教一下这个地方的运算是为了什么。

**Comment by AKACoder** [comment]
> https://github.com/SealSC/SealEVM/blob/1e2e076787dff706df96b32bffc0d5936e4d56da/evmInt256/evmInt256.go#L83-L86
> 
> 看不太明白，想请教一下这个地方的运算是为了什么。

我们使用了big库，该库支持任意bit位数的数值计算，因此会产生超出256bit表示范围的数值。
这个操作是为了将256bit以外的bit位清零，以避免错误的计算，如：
右移操作时，将超出256 bit外的1，错误的移入256bit内，会产生非预期的结果。
